/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as Day1IndexImport } from './routes/day-1/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const Day1IndexRoute = Day1IndexImport.update({
  id: '/day-1/',
  path: '/day-1/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/day-1/': {
      id: '/day-1/'
      path: '/day-1'
      fullPath: '/day-1'
      preLoaderRoute: typeof Day1IndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/day-1': typeof Day1IndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/day-1': typeof Day1IndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/day-1/': typeof Day1IndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/day-1'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/day-1'
  id: '__root__' | '/' | '/day-1/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Day1IndexRoute: typeof Day1IndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Day1IndexRoute: Day1IndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/day-1/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/day-1/": {
      "filePath": "day-1/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
