/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as Day4IndexImport } from './routes/day-4/index'
import { Route as Day3IndexImport } from './routes/day-3/index'
import { Route as Day2IndexImport } from './routes/day-2/index'
import { Route as Day1IndexImport } from './routes/day-1/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const Day4IndexRoute = Day4IndexImport.update({
  id: '/day-4/',
  path: '/day-4/',
  getParentRoute: () => rootRoute,
} as any)

const Day3IndexRoute = Day3IndexImport.update({
  id: '/day-3/',
  path: '/day-3/',
  getParentRoute: () => rootRoute,
} as any)

const Day2IndexRoute = Day2IndexImport.update({
  id: '/day-2/',
  path: '/day-2/',
  getParentRoute: () => rootRoute,
} as any)

const Day1IndexRoute = Day1IndexImport.update({
  id: '/day-1/',
  path: '/day-1/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/day-1/': {
      id: '/day-1/'
      path: '/day-1'
      fullPath: '/day-1'
      preLoaderRoute: typeof Day1IndexImport
      parentRoute: typeof rootRoute
    }
    '/day-2/': {
      id: '/day-2/'
      path: '/day-2'
      fullPath: '/day-2'
      preLoaderRoute: typeof Day2IndexImport
      parentRoute: typeof rootRoute
    }
    '/day-3/': {
      id: '/day-3/'
      path: '/day-3'
      fullPath: '/day-3'
      preLoaderRoute: typeof Day3IndexImport
      parentRoute: typeof rootRoute
    }
    '/day-4/': {
      id: '/day-4/'
      path: '/day-4'
      fullPath: '/day-4'
      preLoaderRoute: typeof Day4IndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/day-1': typeof Day1IndexRoute
  '/day-2': typeof Day2IndexRoute
  '/day-3': typeof Day3IndexRoute
  '/day-4': typeof Day4IndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/day-1': typeof Day1IndexRoute
  '/day-2': typeof Day2IndexRoute
  '/day-3': typeof Day3IndexRoute
  '/day-4': typeof Day4IndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/day-1/': typeof Day1IndexRoute
  '/day-2/': typeof Day2IndexRoute
  '/day-3/': typeof Day3IndexRoute
  '/day-4/': typeof Day4IndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/day-1' | '/day-2' | '/day-3' | '/day-4'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/day-1' | '/day-2' | '/day-3' | '/day-4'
  id: '__root__' | '/' | '/day-1/' | '/day-2/' | '/day-3/' | '/day-4/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Day1IndexRoute: typeof Day1IndexRoute
  Day2IndexRoute: typeof Day2IndexRoute
  Day3IndexRoute: typeof Day3IndexRoute
  Day4IndexRoute: typeof Day4IndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Day1IndexRoute: Day1IndexRoute,
  Day2IndexRoute: Day2IndexRoute,
  Day3IndexRoute: Day3IndexRoute,
  Day4IndexRoute: Day4IndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/day-1/",
        "/day-2/",
        "/day-3/",
        "/day-4/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/day-1/": {
      "filePath": "day-1/index.tsx"
    },
    "/day-2/": {
      "filePath": "day-2/index.tsx"
    },
    "/day-3/": {
      "filePath": "day-3/index.tsx"
    },
    "/day-4/": {
      "filePath": "day-4/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
